Introduce concept of scope & Check whether label is defined
fruits-lab/VitaminC pull request #127
Opened 2024-04-03 16:05 UTC by Lai-YT

- Each scope now associates with a `ScopeKind`. Please refer to _include/scope.hpp_: `struct Scope`.
  - `ScopeStack::PushScope` and `ScopeStack::Add` now require a `ScopeKind`. Modifications have been made in `src/type_checker.cpp` to assign scope kinds to scopes and symbols.

- `ScopeStack` now supports merging the current scope with the next scope. This functionality is implemented in _include/scope.hpp_: `ScopeStack::MergeWithNextScope`.
  - This enhancement specifically addresses including function parameters in the scope of the function body.

- The checking for "Use of undefined label" and "redefinition of label" now utilizes an auxiliary map. This change is implemented in _src/type_checker.cpp_: `<unnamed>::label_defined`.

> [!important]
> Currently, a function scope is opened by a function, but no label is actually added to such a scope (symbol table). This is due to the following reasons:
> 1. Labels reside in their own scope and can only be redefined by labels.
> 2. The redefinition check of a label is performed by looking up the auxiliary map instead of the scope stack. If we were to look up the scope stack, we would need to support looking up a certain kind of scope or a certain kind of symbol, to avoid mistakenly `goto` a variable or assign to a label.
>
> In fact, I also question the usefulness of scope kinds. Although they are defined in the manual, I have yet to discern their semantic differences.
> @leewei05, do you think we should still add the labels into the scope? Or should we ignore the concept of scope kind altogether? Or should we defer this decision and leave the labels as not added?

2024-04-11 07:47 UTC, leewei05 commented
> @leewei05, do you think we should still add the labels into the scope? Or should we ignore the concept of scope kind altogether? Or should we defer this decision and leave the labels as not added?

I think we can keep the concept of scope kind just for now. Couldn't think of certain use cases for utilizing different scope kind, but I think this information would be quite handy if we started to implemented global variables, struct etc.

As for whether we should add labels into the scope, I prefer not to store them into the scope. I think it is easier to implement with the current `label_defined` map. If there's a label that has the same name with an identifier, we will need extra work to check them. Like the following code, there will be two `i` with different scope kind where we will need to check, and we couldn't be sure whether the first `i` is a label or an identifier unless we check their scope kind.

```
#include <stdio.h>

int main() {
    int i = 5;
    goto j;
i:
    i = 4;
    goto end;
j:
    printf("%d\n", i);
    goto i;
    
end:
    printf("%d\n", i);
    return 0;
}
```

2024-04-11 07:49 UTC, leewei05 requested changes
Looking good! Only a few request changes. Or is it better to access key directly instead of `at()`?

2024-04-11 07:49 UTC, leewei05 commented on src/type_checker.cpp
> +      !label_defined[goto_stmt.label];
Use `at()` instead?
```
label_defined.at(goto_stmt.label); 
```

2024-04-11 07:49 UTC, leewei05 commented on src/type_checker.cpp
> +      label_defined[id_labeled_stmt.label]) {
Use `at()` instead?
```
label_defined.at(id_labeled_stmt.label); 
```

2024-04-11 13:24 UTC, Lai-YT commented
Conflict resolved by rebasing. :love_you_gesture:

2024-04-12 06:53 UTC, leewei05 approved these changes
LGTM! Thanks for the great work!

2024-04-12 06:53 UTC, merged